# Generated by Django 4.2.1 on 2023-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100, null=True)),
                ('your_email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('massage', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
