# Generated by Django 4.2.1 on 2023-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='your_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
